This is makeindex, version 2.16 [MiKTeX 23.9.24].
Scanning style file ./main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main.acn....done (164 entries accepted, 0 rejected).
Sorting entries.....done (1531 comparisons).
Generating output file main.acr....done (125 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
